events{
}

http{
    upstream backend_service{
        server backend:3000;
    }

    server {
        listen 80;
        server_name myapp-dev.localhost;

        return 307 https://myapp-dev.localhost:8443$request_uri;
  }


    server {
    listen 443 ssl;
    server_name myapp-dev.local;  

    ssl_certificate     /etc/nginx/ssl/myapp-dev.localhost.pem;
    ssl_certificate_key /etc/nginx/ssl/myapp-dev.localhost-key.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location / {
      proxy_pass http://backend_service;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}