ENV = "dev"
LOG_LEVEL = "INFO"

DATA_ROOT = "src/data"

RAW_DATA_PATH = f"{DATA_ROOT}/raw"
CLEANED_DATA_PATH = f"{DATA_ROOT}/cleaned"
CHUNKS_DATA_PATH = f"{DATA_ROOT}/chunks"
EMBEDDINGS_DATA_PATH = f"{DATA_ROOT}/embeddings/embeddings.npy"


CHUNK_SIZE = 700
CHUNK_OVERLAP = 100
CHUNKING_STRATEGY = "recursive_character"

EMBEDDING_PROVIDER = "huggingface"
EMBEDDING_MODEL_NAME = "BAAI/bge-base-en"
EMBEDDING_DIMENSION = 384

VECTORSTORE_TYPE = "Qdrant"
SIMILARITY_METRIC = "cosine"

RETRIEVER_TOP_K = 5

LLM_PROVIDER = "grok"
LLM_MODE = "hosted"
LLM_MODEL_NAME = "grok-2"
LLM_USED_FROM_DAY = 2
